[package]
name = "fractal"
version = "6.0.0"
authors = ["Julian Sparber <julian@sparber.net>"]
edition = "2021"
rust-version = "1.75"
publish = false

[profile.release]
debug = true
lto = "thin"
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

# Please keep dependencies sorted.
[dependencies]
djb_hash = "0.1"
eyeball-im = "0.4"
futures-channel = "0.3"
futures-util = "0.3"
geo-uri = "0.2"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
html-escape = "0.2"
html2pango = "0.6"
html5gum = "0.5"
image = "0.24"
indexmap = "2"
mime = "0.3"
mime_guess = "2"
once_cell = "1"
pulldown-cmark = "0.9"
qrcode = "0.13"
rand = "0.8"
regex = "1"
rmp-serde = "1"
rqrr = "0.6"
secular = { version = "1", features = ["bmp", "normalization"] }
serde = "1"
serde_json = "1"
strum = { version = "0.25", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["rt", "rt-multi-thread", "sync"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = "2"

# gtk-rs project and dependents. These usually need to be updated together.
adw = { package = "libadwaita", version = "0.6", features = ["v1_4"] }
gst = { version = "0.22", package = "gstreamer" }
gst_base = { version = "0.22", package = "gstreamer-base" }
gst_gtk = { version = "0.12", package = "gst-plugin-gtk4" }
gst_pbutils = { version = "0.22", package = "gstreamer-pbutils" }
gst_play = { version = "0.22", package = "gstreamer-play" }
gst_video = { version = "0.22", package = "gstreamer-video" }
gtk = { package = "gtk4", version = "0.8", features = ["v4_10"] }
shumate = { package = "libshumate", version = "0.5" }
sourceview = { package = "sourceview5", version = "0.8" }

[dependencies.matrix-sdk]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "eec52d7977c6122879a2d25f6ea81d76ea754280"
features = [
    "socks",
    "sso-login",
    "markdown",
    "qrcode",
    "image-rayon",
]

[dependencies.matrix-sdk-ui]
git = "https://github.com/matrix-org/matrix-rust-sdk.git"
rev = "eec52d7977c6122879a2d25f6ea81d76ea754280"
default-features = false
features = ["e2e-encryption", "native-tls"]

[dependencies.ruma]
# version = "0.9.4"
git = "https://github.com/ruma/ruma.git"
rev = "684ffc789877355bd25269451b2356817c17cc3f"
features = [
    "unstable-unspecified",
    "client-api-c",
    "compat-key-id",
    "compat-user-id",
    "compat-empty-string-null",
    "compat-null",
    "compat-optional",
    "compat-unset-avatar",
    "compat-get-3pids",
    "html",
]

# Linux-only dependencies.
[target.'cfg(target_os = "linux")'.dependencies]
ashpd = { version = "0.7", default-features = false, features = [
    "pipewire",
    "tracing",
    "tokio",
] }
oo7 = { version = "0.2", default-features = false, features = [
    "native_crypto",
    "tokio",
    "tracing",
] }
