# Build and publish the docs

include: '.gitlab-ci/pages.yaml'

pages:
  stage: deploy
  variables:
    DOCS_FOLDER: "public"
  rules:
    - changes:
        - src/**/*
        - Cargo.lock
        - Cargo.toml
      when: always
    - when: manual
      allow_failure: true
